/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WorkShop4A;

import static WorkShop4A.Manager.arr;
import static WorkShop4A.Manager.b;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Linh Trang
 */
public class form extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
     DefaultTableModel tb;
     Manager m;
    Book b;
    public form() {
        initComponents();
                tb = (DefaultTableModel) jTable1.getModel();

    }

//    public void isValidNumber( String xNum) {
//        char c;
//        boolean check = true;
//        String s = txtName.getText().trim();
//
//        if (s.isEmpty()) {
//            check = false;
//        }
//        for (int i = 0; i < s.length(); i++) {
//            c = s.charAt(i);
//            if (Character.isDigit(c)) 
//                JOptionPane.showMessageDialog(null, "Name is invalid\r\n");
//              }}
//    
// 
//    
//    
//    public void isValidPrice() {
//        char c;
//        boolean check = true;
//        String s = txtPrice.getText().trim();
//      
//        if (s.isEmpty()) {       
//            JOptionPane.showMessageDialog(null, "please enter price\r\n");                   
//        }
//        for (int i = 0; i < s.length(); i++) {
//            c = s.charAt(i);
//            if (!Character.isDigit(c) ) 
//                JOptionPane.showMessageDialog(null, "Price is invalid\r\n");               
//    }}

     boolean isValidNumber(String xNum) {
        char c;
        int n, i;
        n = xNum.length();
        for (i = 0; i < n; i++) {
            c = xNum.charAt(i);
            if (!(Character.isDigit(c))) {
                return (false);
            }
        }
        return (true);
    }

    boolean isValidPrice(String xp) {
        float num;
        try {
            num = Float.parseFloat(xp);
            return true;
        } catch (Exception e) {
            return false;
        }
    }
    
    

void clear(){
        int n = jTable1.getRowCount();
        for (int i = 0; i < n; i++) {
            tb.removeRow(0);
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnA = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Book ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 68, 54, 17);

        txtID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtID.setText("123");
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID);
        txtID.setBounds(92, 65, 99, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("BOOK");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 10, 64, 27);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Book Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 106, 75, 17);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1033, 90, 0, 0);

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtName);
        txtName.setBounds(92, 103, 133, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Quantity:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(12, 139, 58, 17);

        txtQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtQuantity);
        txtQuantity.setBounds(92, 136, 97, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Price:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(12, 170, 34, 17);

        txtPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtPrice);
        txtPrice.setBounds(92, 167, 97, 23);

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(600, 220, 63, 25);

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(510, 220, 63, 25);

        btnClose.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose);
        btnClose.setBounds(410, 220, 65, 25);

        btnAdd.setFont(btnAdd.getFont().deriveFont((float)14));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(255, 64, 77, 25);

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(255, 103, 77, 25);

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(255, 135, 77, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Book Name", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(400, 50, 330, 140);

        btnA.setText("X");
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });
        getContentPane().add(btnA);
        btnA.setBounds(770, 60, 70, 25);

        btnB.setText("Y");
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });
        getContentPane().add(btnB);
        btnB.setBounds(770, 110, 70, 25);

        btnC.setText("Z");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        getContentPane().add(btnC);
        btnC.setBounds(770, 160, 70, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String ID, name, xquan, xprice;
        int quant;
        float price;
        ID = txtID.getText().trim();
        name = txtName.getText().trim();
        xquan = txtQuantity.getText().trim();
        xprice = txtPrice.getText().trim();
        if (ID.isEmpty() || name.isEmpty() || xquan.isEmpty() || xprice.isEmpty()) {
            JOptionPane.showMessageDialog(this, "data can not be blank.");
            return;
        }
        if (!isValidNumber(xquan)) {
            JOptionPane.showMessageDialog(this, "quantity must be an integer.");
            return;
        }
        if (!isValidPrice(xprice)) {
            JOptionPane.showMessageDialog(this, "Invalid price.");
            return;
        }
        quant = Integer.parseInt(xquan);
        price = Float.parseFloat(xprice);
        m.add(ID, name, quant, price);
        Object[] o = {ID, name, quant, price};
        tb.addRow(o);

        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         int k = jTable1.getSelectedRow();
        if (k == -1) {
            JOptionPane.showMessageDialog(this, "Please select the rows.");
            return;
        }
        tb.removeRow(k);
               
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
//        String id = txtID.getText();
//        String name = txtName.getText();
//        int quantity = Integer.parseInt(txtQuantity.getText());
//        double price = Double.parseDouble(txtPrice.getText());
//        
//        for (BookManament o : list) {
//            if(o.getId().equals(id)){
//                o.setName(name);
//                o.setPrice(price);
//                o.setQuantity(quantity);
//                JOptionPane.showMessageDialog(null, "Updated");
//                break;
//            }
//        }
//        String all = "BookId\tName\tQuantity\tPrice\n";
//        for (BookManament o : list) {
//            all += o.toString();
//        }
//        txtoutput.setText(all);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
         int n = tb.getRowCount();
        if (n <= 0) {
            JOptionPane.showMessageDialog(this, "No rows exist.");
            return;
        }
        int k = JOptionPane.showConfirmDialog(this, "Sure to clear?");
        if (k > 0) {
            return;
        }else{
            for (int i = 0; i < n; i++) {
                tb.removeRow(0);
            }
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
//         tb.setRowCount(0);
//        for (b manager : m) {
//           tb.addRow(new Object[]{
//                b.getBookId(),b.getBookName(),b.getQuantity(),b.getPrice()
//            });
//        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        // TODO add your handling code here:
       // TODO add your handling code here:
        tb.insertRow(0, new Object[3]);
            jTable1.setValueAt("2", 0, 0);
            jTable1.setValueAt("B", 0, 1);
            jTable1.setValueAt(2, 0, 2);
            jTable1.setValueAt(1, 0, 3);       
        tb.insertRow(0, new Object[4]);
            jTable1.setValueAt("1", 0, 0);
            jTable1.setValueAt("A", 0, 1);
            jTable1.setValueAt(2, 0, 2);
            jTable1.setValueAt(1, 0, 3);

    }//GEN-LAST:event_btnAActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        /// TODO add your handling code here:
        clear();
        tb.insertRow(0, new Object[3]);
            jTable1.setValueAt("2", 0, 0);
            jTable1.setValueAt("B", 0, 1);
            jTable1.setValueAt(2, 0, 2);
            jTable1.setValueAt(1, 0, 3);       
        tb.insertRow(0, new Object[4]);
            jTable1.setValueAt("1", 0, 0);
            jTable1.setValueAt("A", 0, 1);
            jTable1.setValueAt(5, 0, 2);
            jTable1.setValueAt(1, 0, 3);
    
    }//GEN-LAST:event_btnBActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
      // TODO add your handling code here:
        clear();
        tb.insertRow(0, new Object[4]);
            jTable1.setValueAt("1", 0, 0);
            jTable1.setValueAt("A", 0, 1);
            jTable1.setValueAt(5, 0, 2);
            jTable1.setValueAt(1, 0, 3);
                                                           
    }//GEN-LAST:event_btnCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables

    
}
